# Problem Statement: **Welcome to AI Town!**

### You’ve been hired as an AI engineer in **AI Town**, a futuristic city powered by artificial intelligence. Your job is to use PyTorch to solve foundational challenges that AI Town faces. Each task requires you to demonstrate your expertise with PyTorch basics.



---



Imports and CUDA

In [1]:
import torch

# Check if CUDA (GPU) is available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")


Using device: cuda




---



**Task1: Inventory Management**

AI Town’s warehouse uses sensors to record the inventory of 5 items every day. Each day’s data is represented as a list of integers (number of units).

In [6]:
#1 Create a PyTorch Tensor from the following inventory data
inventory = [[12, 15, 10, 0, 5],
             [10, 8, 7, 5, 4],
             [20, 10, 15, 5, 2]]

inventory_tensor=torch.tensor(inventory)

In [9]:
#2 Find the total inventory for each item across all days
total_Inventory=inventory_tensor[0,:]+inventory_tensor[1,:]+inventory_tensor[2,:]

# or

# total_inventory=inventory_tensor.sum(dim=0)
total_Inventory

tensor([42, 33, 32, 10, 11])

In [19]:
#3 Find the average inventory per day

avg_inventory=total_Inventory/5
avg_inventory

tensor([8.4000, 6.6000, 6.4000, 2.0000, 2.2000])



---



**Task2: Monitoring Vehicle Flow**

AI Town uses a sensor to monitor the number of vehicles passing through two main roads every hour. The data for one day (24 hours) is represented as two
1×24 tensors.

In [24]:
#1 Simulate this data using PyTorch's Random Functions
# torch.randint(low, high, size)

road1=torch.randint(50,200,(24,))
print(road1)
road2=torch.randint(50,200,(24,))
print(road2)

tensor([110,  55,  52, 148, 125,  88, 120, 182, 191,  67,  58, 102, 135,  56,
        105, 175,  73, 123,  91, 183, 174,  78, 157,  85])
tensor([ 92, 148, 122,  65, 101,  51, 157, 110,  63, 131,  90, 173,  94, 181,
        143,  63, 177,  72, 144, 112, 161,  72, 186, 145])


In [30]:
#2 Write the function to calculate the total vehicle flow for each road across the entire day
road1_sum=road1.sum()
print(road1_sum)
road2_sum=road2.sum()
print(road2_sum)

tensor(2733)
tensor(2853)


In [31]:
#3 Write the function to calculate the total vehicle flow for each hour across both roads
road_sum=road1+road2
print(road_sum)

tensor([202, 203, 174, 213, 226, 139, 277, 292, 254, 198, 148, 275, 229, 237,
        248, 238, 250, 195, 235, 295, 335, 150, 343, 230])




---



**Task3: Fitness Matrix**

The AI Gym tracks members’ fitness scores using a 3×3 matrix for *strength*, *stamina*, and f*lexibility*. Each row represents a different member, and each column represents a specific metric.

In [43]:
#1 Create a 3*3 tensor matrix and multiply the scores of each member by a weight factor: [0.8, 1.2, 1.5]
fitness = torch.tensor([[10, 20, 30],
                        [40, 50, 60],
                        [70, 80, 90]])
weights = torch.tensor([0.8, 1.2, 1.5])
weighted_fitness = weights * fitness
print(weighted_fitness)

tensor([[  8.0000,  24.0000,  45.0000],
        [ 32.0000,  60.0000,  90.0000],
        [ 56.0000,  96.0000, 135.0000]])


In [44]:
#2 Find the row-wise and column-wise maximum scores
row_max = weighted_fitness.max(dim=1) # max for each row
col_max = weighted_fitness.max(dim=0) # max for each column
print(row_max)
print(col_max)

torch.return_types.max(
values=tensor([ 45.,  90., 135.]),
indices=tensor([2, 2, 2]))
torch.return_types.max(
values=tensor([ 56.,  96., 135.]),
indices=tensor([2, 2, 2]))


In [45]:
#3 Transpose the fitness matrix and interpret it's new structure (shape)
transpose_fitness=fitness.t()
transpose_fitness

tensor([[10, 40, 70],
        [20, 50, 80],
        [30, 60, 90]])



---



**Task4: Chain Rule in Action**

AI Lab is running experiments to understand the effect of temperature (
x) on a chemical reaction rate (y). The relationship is given as:
$y = 2x^3 + 5x^2 - 3x + 7$



In [49]:
#1 Use PyTorch to compute 'y' for x = 4

x=torch.tensor(10, requires_grad=True, dtype=torch.float16)
y=2*x**3+5*x**2-3*x+7
y

tensor(2476., dtype=torch.float16, grad_fn=<AddBackward0>)

In [50]:
#2 Calculate dy/dx(gradient) using PyTorch's autograd
y.backward()
x.grad

tensor(697., dtype=torch.float16)



---



**Task5: Camera Calibration**

AI Town’s surveillance cameras need to align their focus. You are given the following matrices for two cameras’ focus adjustments:

In [53]:

camera1 = torch.tensor([[1, 2], [3, 4]])
camera2 = torch.tensor([[5, 6], [7, 8]])


In [58]:
#1 Perform an element-wise multiplication of matrices ( Hadamard Product)
camera=camera1*camera2
camera

tensor([[ 5, 12],
        [21, 32]])

In [59]:
#2 Compute Dot Product of the two matrices
cameradot=torch.matmul(camera1, camera2)
cameradot

tensor([[19, 22],
        [43, 50]])

In [60]:
#3 Compute the Determinant of each matrix
det_camera1 = torch.det(camera1.float())
det_camera2 = torch.det(camera2.float())
print(det_camera1)
print(det_camera2)

tensor(-2.)
tensor(-2.0000)




---



**Task6: Neural Network Foundations**

Our AI University uses simplified single neuron model (perceptron):
$$y = wx + b$$

In [67]:
#1 Create tensors for w  = 2, b = 1, x = [1, 2, 3, 4]

w=torch.tensor(2, requires_grad=True, dtype=torch.float16)
b=torch.tensor(1, requires_grad=True, dtype=torch.float16)
x=torch.tensor([1,2,3,4])

In [68]:
#2 Compute tensors for y
y=w*x+b
y

tensor([3., 5., 7., 9.], dtype=torch.float16, grad_fn=<AddBackward0>)



---

