In [1]:
import numpy as np


In [3]:
revenue_q1=np.array([12,45,76])
revenue_q1.ndim


1

In [5]:
rev=np.array([[1,2567,98],[40,875,6]])
np.sort(rev)

array([[   1,   98, 2567],
       [   6,   40,  875]])

In [15]:
q1=np.array([ #rows are product and col are region usa china india
    [200,220,250],#product 1
    [150,180,210],#product 2
    [300,330,268] #product 2
])
q2=np.array([
    [400,420,440],
    [400,470,400],
    [480,430,468]
])
q1+q2

array([[600, 640, 690],
       [550, 650, 610],
       [780, 760, 736]])

In [14]:
(q2-q1)*100/q1

array([[100.        ,  90.90909091,  76.        ],
       [166.66666667, 161.11111111,  90.47619048],
       [ 60.        ,  30.3030303 ,  74.62686567]])

In [17]:
prices=np.array([[10, 12,11],#prices for product 1
       [8, 9, 10],#prices for product 1
       [15, 16, 17]])#prices for product 1
q1_revenue=q1*prices
q1_revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 4556]])

In [20]:
q1_discount=q1_revenue*0.2
q1_discount

array([[ 400. ,  528. ,  550. ],
       [ 240. ,  324. ,  420. ],
       [ 900. , 1056. ,  911.2]])

In [22]:
net_revenue=q1_revenue-q1_discount
net_revenue

array([[1600. , 2112. , 2200. ],
       [ 960. , 1296. , 1680. ],
       [3600. , 4224. , 3644.8]])

In [24]:
np.sum(q1_discount)

np.float64(5329.2)